CREATE DATABASE ParkingLot
USE ParkingLot
CREATE TABLE CarsTBL(
	CNum INT NOT NULL PRIMARY KEY IDENTITY,
	PNumber VARCHAR(50) NOT NULL,
	Driver VARCHAR(50) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	CarType VARCHAR(50) NOT NULL,
	CarColor VARCHAR(50) NOT NULL
);
CREATE TABLE PlaceTBL(
	PlNum INT NOT NULL PRIMARY KEY IDENTITY,
	Pposition VARCHAR(150) NOT NULL,
	PStatus VARCHAR(50) NOT NULL,
);
CREATE TABLE ParkingTBL(
	PCode INT NOT NULL PRIMARY KEY IDENTITY(100,1),
	Car INT NOT NULL,
	Date DATE NOT NULL,
	Duration INT NOT NULL,
	Amount INT NOT NULL,
	Place INT NOT NULL,
	CONSTRAINT [FK1] FOREIGN KEY ([Car]) REFERENCES [CarsTBL]([CNum]),
	CONSTRAINT [FK2] FOREIGN KEY ([Place]) REFERENCES [PlaceTBL]([PlNum])
);